version: '3'
# Список наших сервисов (контейнеров)
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"

        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./www:/var/www
        links:
            - php
    php:
        build: .
        volumes:
            - ./www:/var/www
        healthcheck:
          test: ["CMD", "curl 127.0.0.1:80 | grep -w works"]
          interval: 1s
          timeout: 3s
          retries: 30